labels:
  - name: bug
    color: ff0000
    description: Something isn't working
  - name: enhancement
    color: 0e8a16
    description: New feature or request
  - name: docs
    color: 0075ca
    description: Documentation only changes
  - name: security
    color: b60205
    description: Security-related issue
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: chore
    color: ededed
    description: Routine tasks
